### ISSUE TITLE
How to save images in tiff format?

### ISSUE THREAD

**Issue by hugonbgg** [nguyenvanthi2020/Sentinel2-Download#5]
I tried to use the 'google drive' option but it didn't work.

**Comment by mikedufty** [comment]
In what way did it not work? Did you get an error message or is the image not there?
I just tried and it works for me.
The image will be in a folder called image_gee in your google drive.  Is the folder missing altogether for you? or just empty?
It appears immediately online for me, but can take a while to sync to computer.

**Comment by hugonbgg** [comment]
They were in the folder on google drive, I thought I saved it in the local folder, but it was online. Thanks for the clarification!
